// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var wkyApiCreateBatchTaskModel = WkyApiCreateBatchTaskModel.FromJson(jsonString);

namespace WkyApiSharp.Service.Model.CreateBatchTask
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WkyApiCreateBatchTaskModel
    {
        [JsonProperty("path")]
        public string Path { get; set; }

        [JsonProperty("tasks")]
        public Task[] Tasks { get; set; }
    }

    public partial class Task
    {
        [JsonProperty("btSub")]
        [JsonConverter(typeof(DecodeArrayConverter))]
        public long[] BtSub { get; set; }

        [JsonProperty("cid")]
        public string Cid { get; set; }

        [JsonProperty("filesize")]
        public long Filesize { get; set; }

        [JsonProperty("gcid")]
        public string Gcid { get; set; }

        [JsonProperty("localfile")]
        public string Localfile { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("ref_url")]
        public string RefUrl { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class WkyApiCreateBatchTaskModel
    {
        public static WkyApiCreateBatchTaskModel FromJson(string json) => JsonConvert.DeserializeObject<WkyApiCreateBatchTaskModel>(json, WkyApiSharp.Service.Model.CreateBatchTask.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this WkyApiCreateBatchTaskModel self) => JsonConvert.SerializeObject(self, WkyApiSharp.Service.Model.CreateBatchTask.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class DecodeArrayConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long[]);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            reader.Read();
            var value = new List<long>();
            while (reader.TokenType != JsonToken.EndArray)
            {
                var converter = ParseStringConverter.Singleton;
                var arrayItem = (long)converter.ReadJson(reader, typeof(long), null, serializer);
                value.Add(arrayItem);
                reader.Read();
            }
            return value.ToArray();
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (long[])untypedValue;
            writer.WriteStartArray();
            foreach (var arrayItem in value)
            {
                var converter = ParseStringConverter.Singleton;
                converter.WriteJson(writer, arrayItem, serializer);
            }
            writer.WriteEndArray();
            return;
        }

        public static readonly DecodeArrayConverter Singleton = new DecodeArrayConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
