// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var wkyApiCreateTaskModel = WkyApiCreateTaskModel.FromJson(jsonString);

namespace WkyApiSharp.Service.Model.CreateTask
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WkyApiCreateTaskModel
    {
        [JsonProperty("path")]
        public string Path { get; set; }

        [JsonProperty("tasks")]
        public Task[] Tasks { get; set; }
    }

    public partial class Task
    {
        [JsonProperty("filesize")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Filesize { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("infohash")]
        public string Infohash { get; set; }
    }

    public partial class WkyApiCreateTaskModel
    {
        public static WkyApiCreateTaskModel FromJson(string json) => JsonConvert.DeserializeObject<WkyApiCreateTaskModel>(json, WkyApiSharp.Service.Model.CreateTask.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this WkyApiCreateTaskModel self) => JsonConvert.SerializeObject(self, WkyApiSharp.Service.Model.CreateTask.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
